project:
  type: website

website:
  title: "vielser-skilsmisser2DR"
  contents: 
   - href: index.qmd
     text: Home
    -href: dashboard.qmd
     text: Dashboard 

format:
  html:
    theme: journal
    css: styles.css
    toc: true



